services:
  - type: worker
    name: tayp-uploads-worker
    env: node
    rootDir: workers/uploads
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: "18.18.0"
